# -*- coding: utf-8 -*-
"""notes_generator code

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GZcoR4og24_8_6UvkN8XC02tkW8SBrLu
"""

!pip install sentence-transformers;

from transformers import pipeline

notes_generator = pipeline("text-generation", model = "gpt2")
chapter=input("enter chapter name:")

prompt_notes = f"""write detailed study notes for {chapter}
include explanation, example and key points
"""
detailed_notes = notes_generator(
  prompt_notes,
  max_length=300,
  num_return_sequences=1,
)
print(detailed_notes[0]["generated_text"])
prompt_summary = f"Summarize the following study notes for chapter {chapter}:\n{detailed_notes[0]['generated_text']}"
summary = notes_generator(
  prompt_summary,
  max_length=200,
  num_return_sequences=1
)
print("\n one page summary:")
print(summary[0]['generated_text'])

prompt_definition = f"""list important definition and formulas from the chapter:{chapter}
use bulletpoints
"""
definition = notes_generator(
  prompt_definition,
  max_length=200,
  num_return_sequences=1
)
print("\n important definitions:")
print(definition[0]['generated_text'])