# -*- coding: utf-8 -*-
"""sentence simlarity project code

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tVIldk1e-jwTfJWQ4hmSnHlSGlvvKlAl
"""

!pip install sentence-transformers

from sentence_transformers import SentenceTransformer, util
model = SentenceTransformer('all-MiniLM-L6-v2')
text1 = input(" enter text 1: ")
text2 = input(" enter text 2: ")
embedding1 = model.encode(text1)
embedding2 = model.encode(text2)
simlarity = util.cos_sim(embedding1, embedding2)
print("\nsimlarity score:",round(float(simlarity),2))
if simlarity > 0.75:
      print("simlarity level : high")
elif simlarity > 0.4:
      print("simlarity level : medium")
else:
      print("simlarity level : low")